project:
  type: website
  output-dir: docs

website:
  title: "Emrecan Serin | Analytics Lab"
  navbar:
    search: false
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Assignments
        href: assignments.qmd
      - text: Project
        href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu660-spring2026-emreserincan-design
      - icon: linkedin
        href: https://www.linkedin.com/in/serinemrecan/

  page-navigation: true
  back-to-top-navigation: true

  page-footer:
    center: "Emrecan Serin • EMU660 • Spring '26"
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false


editor: visual

